#pragma once

#define RGB_MATRIX_STARTUP_HUE 255
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_DISABLE_TIMEOUT 300000
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_DISABLE_WITH_FADE_OUT
#define RGB_FADE_IN